# Generated by Django 4.2.1 on 2023-05-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=300)),
                ('lastName', models.CharField(max_length=300)),
                ('DOB', models.DateField(verbose_name='Geburtsdatum')),
                ('anerkennung', models.BooleanField(default=False)),
                ('ausbildung', models.BooleanField(default=False)),
            ],
        ),
    ]
