# Generated by Django 4.2.1 on 2023-05-29 16:08

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_firstname_alter_student_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='anerkennungFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BFKV/antraege/anerkennung_WE')),
            ],
        ),
        migrations.CreateModel(
            name='arbeitserlaubnisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visa/arbeitserlaubnis/')),
            ],
        ),
        migrations.CreateModel(
            name='aufenthaltserlaubnisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visa/aufenthaltserlaubnis/')),
            ],
        ),
        migrations.CreateModel(
            name='beschaeftigungsverhaeltnisFileEXE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/beschaeftigungsverhaeltnis/EXE/')),
            ],
        ),
        migrations.CreateModel(
            name='beschaeftigungsverhaeltnisFilePH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/beschaeftigungsverhaeltnis/PH/')),
            ],
        ),
        migrations.CreateModel(
            name='bewertungFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BFKV/bewertung')),
            ],
        ),
        migrations.CreateModel(
            name='bildungsgutscheinFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/bildungsgutschein')),
            ],
        ),
        migrations.CreateModel(
            name='certificatesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BFKV/certificates')),
            ],
        ),
        migrations.CreateModel(
            name='copyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/copy/')),
            ],
        ),
        migrations.CreateModel(
            name='cvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/cv/')),
            ],
        ),
        migrations.CreateModel(
            name='erlaubnisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BFKV/antraege/erlaubnis_gesundheitsberufe')),
            ],
        ),
        migrations.CreateModel(
            name='examFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/exam/')),
            ],
        ),
        migrations.CreateModel(
            name='fuehrungszeugnisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/fuerungszeugnis/')),
            ],
        ),
        migrations.CreateModel(
            name='letterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/letter/')),
            ],
        ),
        migrations.CreateModel(
            name='misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=students.models.setdir)),
            ],
        ),
        migrations.CreateModel(
            name='passFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/pass/')),
            ],
        ),
        migrations.CreateModel(
            name='personalbogenFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/personalbogen/')),
            ],
        ),
        migrations.CreateModel(
            name='rentalcontractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='contracts/renting')),
            ],
        ),
        migrations.CreateModel(
            name='schuldanerkenntnisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/schuldanerkenntnis')),
            ],
        ),
        migrations.CreateModel(
            name='stellenbeschreibungFileEXE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/stellenbeschreibung/EXE')),
            ],
        ),
        migrations.CreateModel(
            name='stellenbeschreibungFilePH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/stellenbeschreibung/PH')),
            ],
        ),
        migrations.CreateModel(
            name='transcriptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/transcript/')),
            ],
        ),
        migrations.CreateModel(
            name='translationsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bericht/translations/')),
            ],
        ),
        migrations.CreateModel(
            name='verzichtserklaerungFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BFKV/verzichtserklaerung')),
            ],
        ),
        migrations.CreateModel(
            name='vollmachtFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BFKV/vollmacht')),
            ],
        ),
        migrations.CreateModel(
            name='vorabzustimmungFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BFKV/vorabzustimmung')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='PHorEXE',
            field=models.IntegerField(choices=[(0, 'Pflegehelfer:in'), (1, 'Examinierte Fachkraft')], default=None),
        ),
        migrations.CreateModel(
            name='visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbeitserlaubnis', models.ManyToManyField(to='students.arbeitserlaubnisfile')),
                ('aufenthaltserlaubnis', models.ManyToManyField(to='students.aufenthaltserlaubnisfile')),
            ],
        ),
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschaeftigungsverhaeltnis', models.ManyToManyField(to='students.beschaeftigungsverhaeltnisfileph')),
                ('bildungsgutschein', models.ManyToManyField(to='students.bildungsgutscheinfile')),
                ('rentalcontract', models.ManyToManyField(to='students.rentalcontractfile')),
                ('schuldanerkenntnis', models.ManyToManyField(to='students.schuldanerkenntnisfile')),
                ('stellenbeschreibung', models.ManyToManyField(to='students.stellenbeschreibungfileph')),
            ],
        ),
        migrations.CreateModel(
            name='BFKV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anerkennung', models.ManyToManyField(to='students.anerkennungfile')),
                ('bewertung', models.ManyToManyField(to='students.bewertungfile')),
                ('certificates', models.ManyToManyField(to='students.certificatesfile')),
                ('erlaubnis', models.ManyToManyField(to='students.erlaubnisfile')),
                ('verzichtserklaerung', models.ManyToManyField(to='students.verzichtserklaerungfile')),
                ('vollmacht', models.ManyToManyField(to='students.vollmachtfile')),
                ('vorabzustimmung', models.ManyToManyField(to='students.vorabzustimmungfile')),
            ],
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pass', models.ManyToManyField(to='students.passfile')),
                ('copy', models.ManyToManyField(to='students.copyfile')),
                ('cv', models.ManyToManyField(to='students.cvfile')),
                ('exam', models.ManyToManyField(to='students.examfile')),
                ('fuehrungszeugnis', models.ManyToManyField(to='students.fuehrungszeugnisfile')),
                ('letter', models.ManyToManyField(to='students.letterfile')),
                ('personalbogen', models.ManyToManyField(to='students.personalbogenfile')),
                ('transcript', models.ManyToManyField(to='students.transcriptfile')),
                ('translations', models.ManyToManyField(to='students.translationsfile')),
            ],
        ),
    ]
