# Generated by Django 4.2.1 on 2023-06-08 11:56

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_anerkennungfile_arbeitserlaubnisfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='miscFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=students.models.setdir)),
            ],
        ),
        migrations.RemoveField(
            model_name='misc',
            name='file',
        ),
        migrations.AlterField(
            model_name='anerkennungfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='BFKV/antraege/anerkennung_WE'),
        ),
        migrations.AlterField(
            model_name='arbeitserlaubnisfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='visa/arbeitserlaubnis/'),
        ),
        migrations.AlterField(
            model_name='aufenthaltserlaubnisfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='visa/aufenthaltserlaubnis/'),
        ),
        migrations.AlterField(
            model_name='beschaeftigungsverhaeltnisfileexe',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/beschaeftigungsverhaeltnis/EXE/'),
        ),
        migrations.AlterField(
            model_name='beschaeftigungsverhaeltnisfileph',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/beschaeftigungsverhaeltnis/PH/'),
        ),
        migrations.AlterField(
            model_name='bewertungfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='BFKV/bewertung'),
        ),
        migrations.AlterField(
            model_name='bildungsgutscheinfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/bildungsgutschein'),
        ),
        migrations.AlterField(
            model_name='certificatesfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='BFKV/certificates'),
        ),
        migrations.AlterField(
            model_name='copyfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/copy/'),
        ),
        migrations.AlterField(
            model_name='cvfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/cv/'),
        ),
        migrations.AlterField(
            model_name='erlaubnisfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='BFKV/antraege/erlaubnis_gesundheitsberufe'),
        ),
        migrations.AlterField(
            model_name='examfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/exam/'),
        ),
        migrations.AlterField(
            model_name='fuehrungszeugnisfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/fuerungszeugnis/'),
        ),
        migrations.AlterField(
            model_name='letterfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/letter/'),
        ),
        migrations.AlterField(
            model_name='passfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/pass/'),
        ),
        migrations.AlterField(
            model_name='personalbogenfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/personalbogen/'),
        ),
        migrations.AlterField(
            model_name='rentalcontractfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/renting'),
        ),
        migrations.AlterField(
            model_name='schuldanerkenntnisfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/schuldanerkenntnis'),
        ),
        migrations.AlterField(
            model_name='stellenbeschreibungfileexe',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/stellenbeschreibung/EXE'),
        ),
        migrations.AlterField(
            model_name='stellenbeschreibungfileph',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/stellenbeschreibung/PH'),
        ),
        migrations.AlterField(
            model_name='transcriptfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/transcript/'),
        ),
        migrations.AlterField(
            model_name='translationsfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bericht/translations/'),
        ),
        migrations.AlterField(
            model_name='verzichtserklaerungfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='BFKV/verzichtserklaerung'),
        ),
        migrations.AlterField(
            model_name='vollmachtfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='BFKV/vollmacht'),
        ),
        migrations.AlterField(
            model_name='vorabzustimmungfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='BFKV/vorabzustimmung'),
        ),
        migrations.AddField(
            model_name='misc',
            name='misc',
            field=models.ManyToManyField(to='students.miscfile'),
        ),
    ]
