# Generated by Django 4.2.1 on 2023-06-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_miscfile_remove_misc_file_alter_anerkennungfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='klasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='klasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.klasse'),
        ),
    ]
